include theos/makefiles/common.mk

BUNDLE_NAME = AOPSwitch
AOPSwitch_FILES = Switch.x
AOPSwitch_FRAMEWORKS = UIKit
AOPSwitch_LIBRARIES = flipswitch
AOPSwitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk